[project]
  name = "ULTRASHILL"
  version = "1.0.0"

[framework]
  type = "bepinex"
  version = "5.4.22"

[game]
  path = "/home/eden/.steam/debian-installation/steamapps/common/ULTRAKILL"
  deploy_dir = "BepInEx/plugins"

[build]
  configuration = "Debug"
